# Generated by Django 4.1.5 on 2023-01-05 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountantApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='creator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_Current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='entityID',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
