# Generated by Django 4.1.5 on 2023-01-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountantApp', '0002_report_creator_report_is_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=False)),
                ('TransID', models.BigIntegerField(default=False)),
                ('Users', models.CharField(max_length=50)),
                ('ReportName', models.CharField(max_length=100)),
                ('ReportType', models.CharField(max_length=100)),
                ('ReportLen', models.IntegerField(default=False)),
                ('ReportWidth', models.IntegerField(default=False)),
                ('ReportTotal', models.IntegerField(default=False)),
                ('ReportAverage', models.IntegerField(default=False)),
                ('ReportStdDevation', models.IntegerField(default=False)),
            ],
        ),
    ]
