# Generated by Django 4.1.5 on 2023-01-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountantApp', '0003_reportstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountantName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='reportstats',
            old_name='Users',
            new_name='Accountant',
        ),
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountantApp.accountant')),
            ],
        ),
    ]
